/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MathContract } from "./Math";
import { NFTPlatformContract } from "./NFTPlatform";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Math"): MathContract;
      require(name: "NFTPlatform"): NFTPlatformContract;
    }
  }
}

export { MathContract, MathInstance } from "./Math";
export { NFTPlatformContract, NFTPlatformInstance } from "./NFTPlatform";
