/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CollateralTokenContract } from "./CollateralToken";
import { ECDSAContract } from "./ECDSA";
import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { IERC1155ErrorsContract } from "./IERC1155Errors";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20ErrorsContract } from "./IERC20Errors";
import { IERC721Contract } from "./IERC721";
import { IERC721ErrorsContract } from "./IERC721Errors";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MathContract } from "./Math";
import { NFTPlatformContract } from "./NFTPlatform";
import { OwnableContract } from "./Ownable";
import { StringsContract } from "./Strings";
import { USDCTokenContract } from "./USDCToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CollateralToken"): CollateralTokenContract;
      require(name: "ECDSA"): ECDSAContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "IERC1155Errors"): IERC1155ErrorsContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Errors"): IERC20ErrorsContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Errors"): IERC721ErrorsContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Math"): MathContract;
      require(name: "NFTPlatform"): NFTPlatformContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Strings"): StringsContract;
      require(name: "USDCToken"): USDCTokenContract;
    }
  }
}

export {
  CollateralTokenContract,
  CollateralTokenInstance,
} from "./CollateralToken";
export { ECDSAContract, ECDSAInstance } from "./ECDSA";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  IERC1155ErrorsContract,
  IERC1155ErrorsInstance,
} from "./IERC1155Errors";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IERC20ErrorsContract, IERC20ErrorsInstance } from "./IERC20Errors";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export { IERC721ErrorsContract, IERC721ErrorsInstance } from "./IERC721Errors";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MathContract, MathInstance } from "./Math";
export { NFTPlatformContract, NFTPlatformInstance } from "./NFTPlatform";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { StringsContract, StringsInstance } from "./Strings";
export { USDCTokenContract, USDCTokenInstance } from "./USDCToken";
